// Port of internal/server/handlers_llms.go. Content is kept identical to the
// self-host server; only ${base} (the public base URL) is substituted.

export function llmsTxt(base: string): string {
  return [
    "# AgentGate",
    "",
    "> Self-hosted encrypted diff & file sharing. AES-256-GCM end-to-end encryption, single binary, SQLite storage, 7-day default auto-expiry.",
    "",
    "AgentGate encrypts code diffs and files client-side before uploading. The server never sees plaintext. Recipients need the passphrase to decrypt.",
    "",
    "## Docs",
    "",
    `- [Full LLM reference](${base}/llms-full.txt): Complete API, CLI, encryption, and payload format details for building integrations`,
    "- [Source code](https://github.com/siygle/agentgate): GitHub repository with README, issues, and releases",
    "- [CLI releases](https://github.com/siygle/agentgate/releases): Prebuilt binaries for all platforms",
    "",
    "## API",
    "",
    `- [POST /api/diff](${base}/llms-full.txt): Create an encrypted diff — send JSON with encrypted_data containing ciphertext, iv, and salt`,
    `- [POST /api/files](${base}/llms-full.txt): Create an encrypted file bundle — same format, preview URL uses /f/ prefix`,
    "",
    "## Optional",
    "",
    "- [Go module](https://pkg.go.dev/github.com/siygle/agentgate): Go package documentation on pkg.go.dev",
    "",
  ].join("\n");
}

export function llmsFullTxt(base: string): string {
  return [
    "# AgentGate",
    "",
    "> Self-hosted encrypted diff & file sharing. AES-256-GCM end-to-end encryption, single binary, SQLite storage, 7-day default auto-expiry.",
    "",
    "AgentGate encrypts code diffs and files client-side before uploading. The server never sees plaintext. Recipients need the passphrase to decrypt.",
    "",
    `Server: ${base}`,
    "",
    "## CLI Installation",
    "",
    "Install with Go:",
    "",
    "    go install github.com/siygle/agentgate/cmd/agentgate@latest",
    "",
    "Or download a prebuilt binary from [GitHub Releases](https://github.com/siygle/agentgate/releases).",
    "",
    "## CLI Setup",
    "",
    "Set the server URL (required) and generate an encryption passphrase:",
    "",
    `    export AGENTGATE_SERVER=${base}`,
    "    agentgate key-gen",
    "    source ~/.zshrc  # or ~/.bashrc",
    "",
    "## CLI Commands",
    "",
    "- `agentgate git-latest`: Share the latest commit diff",
    "- `agentgate git-staged`: Share staged changes",
    "- `agentgate files <paths...>`: Share one or more files",
    "- `agentgate docs <file|dir>`: Share rendered Markdown/MDX documents",
    "- `agentgate plan <file|dir>`: Share a visual plan bundle",
    "- `agentgate webapp <dir>`: Share a runnable static webapp containing index.html",
    "- `agentgate key-gen [key]`: Generate or set encryption passphrase",
    "- `agentgate key-get`: Print current passphrase",
    "",
    "All upload commands accept `-s <server>`, `-p <passphrase>`, `-t <duration>`, and `--no-expiry` flags to override environment variables and retention.",
    "",
    "## Environment Variables",
    "",
    "- `AGENTGATE_SERVER`: Server URL (required, no default)",
    "- `AGENTGATE_PASSPHRASE`: Encryption passphrase",
    "",
    "## API Reference",
    "",
    "### POST /api/diff",
    "",
    "Create an encrypted diff. Request body:",
    "",
    "```json",
    "{",
    '  "encrypted_data": {',
    '    "ciphertext": "<base64-encoded ciphertext>",',
    '    "iv": "<base64-encoded initialization vector>",',
    '    "salt": "<base64-encoded salt>"',
    "  }",
    "}",
    "```",
    "",
    "Response (201 Created):",
    "",
    "```json",
    "{",
    '  "success": true,',
    '  "data": {',
    `    "preview_url": "${base}/p/<id>",`,
    '    "id": "<id>"',
    "  }",
    "}",
    "```",
    "",
    "### POST /api/files",
    "",
    "Create an encrypted file bundle. Same request/response format as POST /api/diff. The preview URL uses `/f/<id>` instead of `/p/<id>`.",
    "",
    "## Encryption Details",
    "",
    "- Algorithm: AES-256-GCM",
    "- Key derivation: PBKDF2-SHA256 with 600,000 iterations",
    "- Encryption is performed client-side only",
    "- The server stores only ciphertext, IV, and salt",
    "- The passphrase is never transmitted to the server",
    "",
    "## Plaintext Payload Formats",
    "",
    "These are the JSON structures that get encrypted before being sent to the API.",
    "",
    "### Diff payload (before encryption)",
    "",
    "```json",
    "{",
    '  "title": "commit subject or description",',
    '  "files": [',
    "    {",
    '      "filename": "path/to/file.go",',
    '      "language": "go",',
    '      "patch": "diff --git a/... unified diff content"',
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "### Files payload (before encryption)",
    "",
    "```json",
    "{",
    '  "files": [',
    "    {",
    '      "title": "filename.go",',
    '      "content": "file content as string"',
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "## Source Code",
    "",
    "- [GitHub repository](https://github.com/siygle/agentgate)",
    "- [CLI releases](https://github.com/siygle/agentgate/releases)",
    "- [Go module](https://pkg.go.dev/github.com/siygle/agentgate)",
    "",
    "## Creating a Skill",
    "",
    "To create a skill or integration for AgentGate CLI, an agent needs to:",
    "",
    "1. Check that `agentgate` is installed (run `agentgate key-get` to verify)",
    "2. If not installed, run `go install github.com/siygle/agentgate/cmd/agentgate@latest`",
    "3. Ensure `AGENTGATE_SERVER` and `AGENTGATE_PASSPHRASE` are set",
    "4. Use the CLI commands to share diffs, files, docs, plans, or webapps",
    "5. Present the public Preview/Docs/Plan/App URL to the user",
    "6. Keep the passphrase and Manage URL private unless the user explicitly asks for ownership controls",
    "",
    "Example workflow for sharing the latest commit:",
    "",
    `    agentgate git-latest -s ${base}`,
    "",
    "The command prints a human-readable URL line, such as `Preview URL: https://...`. Extract that URL and share it with the user. Do not reveal `AGENTGATE_PASSPHRASE` in chat.",
    "",
  ].join("\n");
}
